services:
  php:
    build:
      context: ./laravel
      dockerfile: Dockerfile
    container_name: app-php
    working_dir: /var/www
    volumes:
      - ./laravel:/var/www
    networks:
      - reserve-net
    env_file: laravel/.env
    command: php artisan serve --host=0.0.0.0 --port=8000

  js:
    image: node:18
    container_name: app-js
    working_dir: /app
    volumes:
      - ./react:/app
    command: sh -c "tail -f /dev/null"
    networks:
      - reserve-net

  nginx:
    image: nginx:latest
    container_name: app-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d/
      - ./react/dist:/var/www/react/dist
      - ./laravel:/var/www
    depends_on:
      - php
      - js
    networks:
      - reserve-net

  db:
    image: mysql:8.0
    container_name: app-db
    environment:
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - reserve-db:/var/lib/mysql
    networks:
      - reserve-net
    env_file: laravel/.env

volumes:
  reserve-db:


networks:
  reserve-net:
